# Jekyll configuration for Open SDG platform
#
# You will need to change all of the capitalized variables below according
# to your Github setup. For example, if your site and data repositories are:
# -- https://github.com/my-awesome-github-org/my-awesome-site-repo
# -- https://github.com/my-awesome-github-org/my-awesome-data-repo
# Then you would want to make these replacements throughout this file:
# -- replace "MY-GITHUB-ORG" with "my-awesome-github-org"
# -- replace "OPEN-SDG-SITE-STARTER" with "my-awesome-site-repo"
# -- replace "OPEN-SDG-DATA-STARTER" with "my-awesome-data-repo"

# Replace this title as needed.
title: City of Los Angeles Indicators For The Sustainable Development Goals
# Replace the baseurl with the name of this repository.
baseurl: "/open-sdg-site-starter"
url: ""
data_dir: data
environment: staging
# Replace MY-GITHUB-ORG and OPEN-SDG-DATA-STARTER as needed.
remotedatabaseurl: "https://angelamhkim.github.io/open-sdg-data-starter"

jekyll_get_json:
  - data: meta
    # Replace MY-GITHUB-ORG and OPEN-SDG-DATA-STARTER as needed.
    json: 'https://angelamhkim.github.io/open-sdg-data-starter/meta/all.json'
  - data: headlines
    # Replace MY-GITHUB-ORG and OPEN-SDG-DATA-STARTER as needed.
    json: 'https://angelamhkim.github.io/open-sdg-data-starter/headline/all.json'
  - data: schema
    # Replace MY-GITHUB-ORG and OPEN-SDG-DATA-STARTER as needed.
    json: 'https://angelamhkim.github.io/open-sdg-data-starter/meta/schema.json'
  - data: reporting
    json: 'https://angelamhkim.github.io/open-sdg-data-starter/stats/reporting.json'
  - data: translations
    json: 'https://open-sdg.github.io/sdg-translations/translations-0.5.1.json'

analytics:
  ga_prod: ''

# Social media accounts.
twitter: 'MyTwitterAccount'

# Replace the email addresses below.
email_contacts:
  questions: angelamhkim@gmail.com
  suggestions: angelamhkim@gmail.com
  functional: angelamhkim@gmail.com

# Github Repo for Data
# Replace this value as needed.
repo_name: open-sdg-data-starter
branch: develop
# Replace this value as needed.
org_name: angelamhkim

# Build settings
markdown: kramdown

# Travis Support
exclude: [vendor, scripts, remotedata]

# International Support
# Eg name: Australia and adjective: Australian
country:
  name: City of Los Angeles
  adjective: Angeleno

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# Menu
menu:
  # Use these to customise the main navigation.
  - path: /
    translation_key: general.goals
  - path: /reporting-status
    # The "translation_key" refers to the key in the SDG Translations repository.
    translation_key: data summary
  - path: /publications/
    translation_key: menu.publications 
  - path: /about
    translation_key: menu.about
  - path: /faq
    translation_key: menu.faq
  - path: /dashboard
    translation_key: urban dashboard


# Configure the text (or "translation key") to be used on the
# non-global metadata tab.
non_global_metadata: Local Metadata

# The list of languages that are translated. The first one is the default.
languages:
  - en

# This makes sure that all pages have a language.
defaults:
  -
    scope:
      path: ""
    values:
      language: "en"

# Set where to point to for goal images.
goal_image_base: https://open-sdg.github.io/sdg-translations/assets/img/goals

# Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme
  - jekyll-get-json
  - jekyll-open-sdg-plugins

# Tell the Remote Theme plugin to use the Open SDG platform (Jekyll theme).
remote_theme: brockfanning/open-sdg@chartjs-component-cleanup

# Apply any custom CSS.
custom_css:
  - /assets/css/custom.css
  
# Apply any custom Javacript.
custom_js:
  - /assets/js/custom.js

  
#Mapping
map_options:
  # Control the limits on zooming in/out in the map:
minZoom: 5
maxZoom: 10
# If you would like to use tile (background) imagery, use these:
tileURL: https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.pngaccess_token={accessToken}
tileOptions:
  id: mapbox.light
  accessToken: pk.eyJ1IjoibGluZGFtZWppYSIsImEiOiJjazE4M2J3cmcwNnk2M25wMXVwcjR1aG5In0.vJ1t8dRbljaPHrD4NuyVkg
  attribution: <a href="https://www.mapbox.com">Mapbox</a>
# Control the choropleth color range. See https://gka.github.iochroma.js/#chroma-brewer
colorRange: chroma.brewer.BuGn
# Set the color for boundaries that have no data.
noValueColor: #f0f0f0
# For documentation on the style options below, see here:
# https://leafletjs.com/reference-1.4.0.html#path-option
# Set the default style for boundaries in the map:
styleNormal:
  weight: 1
  opacity: 1
  color: #888
  fillOpacity: 0.7
# Set the style for boundaries that have been selected/highlighted:
styleHighlighted:
  weight: 1
  opacity: 1
  color: #111
  fillOpacity: 0.7
# Set the style for top-level boundaries that are displaying inother layers.
# Note: This is only applicable when using the "nested zoom"feature (see below).
styleStatic:
  weight: 2
  opacity: 1
  fillOpacity: 0
  color: #172d44
  dashArray: 5,5
    
map_layers:
-
  # [REQUIRED] The URL to the GeoJSON file for this layer:
  serviceUrl: http://s3-us-west-2.amazonaws.comboundaries.latimes.com/archive/1.0/boundary-setla-city-council-districts-2012.geojson
  # [REQUIRED] The property in `properties` for each boundary'shuman-readable name
  nameProperty: name
  # [REQUIRED] The property in `properties` for each boundary'sunique ID (GeoCode).
  idProperty: external_id
  # The minimum zoom at which this layer should be visible.
  min_zoom: 0
  # The maximum zoom at which this layer should be visible.
  max_zoom: 20
  # Whether or not these boundaries should display statically onlower layers.
  staticBorders: false
